### ISSUE TITLE
Fix PHP warnings spamming system.log

### ISSUE THREAD

**Issue by mwgamble** [ericthehacker/magento-configscopehints#7]
On lines 57 and 167 of EW_ConfigScopeHints_Block_Adminhtml_System_Config_Form, a variable named $inherit is referenced. This variable is not defined before being used, which (at least in my testing) means that for every setting on a page in the system configuration, two error messages are added to the system.log file. Just wondering what the intent of this variable was, and if it should be removed or changed.

**Comment by ericthehacker** [comment]
@mwgamble 
Thanks for bringing this to my attention -- modules which emit lots of warnings are one of my pet peeves.

Interesting. The first instance is directly copied from the core and the second is only a slightly modified version of the core usage -- see `Mage_Adminhtml_Block_System_Config_Form::initFields()`, lines 308 and 416 (on EE 1.14.1.0, anyway). 

I've quickly created a branch which declares the variable before it is used: https://github.com/ericthehacker/magento-configscopehints/compare/develop...feature/form-warning-fix?expand=1 .

Unfortunately I don't have any time to do a sanity check at the moment, but if you'd like to give this branch a shot, please go ahead. Otherwise, I'll review it more closely on Monday and then merge it in.

**Comment by mwgamble** [comment]
It would appear that the problem stems from this method changing in Magento 1.7 CE (roughly 1.12 EE), where any earlier versions will encounter the issue I reported. This is probably related to #6. I can't see an obvious workaround for compatibility, so perhaps this should be addressed with a note on minimum required Magento versions.
